/**
 * Bundled offline emoji catalog for the composer emoji picker.
 * No network fetch — the whole catalog ships in the app bundle.
 * Categories mirror the sections rendered by `EmojiPickerPanel`; category
 * slugs are i18n key suffixes (`emoji.category.<slug>`).
 */

export type EmojiEntry = {
  char: string;
  name: string;
  keywords: string[];
  category: string;
};

/** Stable category order (also the render/section order in the picker). */
export const EMOJI_CATEGORIES: string[] = [
  "smileys",
  "gestures",
  "people",
  "animals",
  "food",
  "activities",
  "travel",
  "objects",
  "symbols",
];

type RawEmoji = [char: string, name: string, keywords: string[]];

function withCategory(category: string, items: RawEmoji[]): EmojiEntry[] {
  return items.map(([char, name, keywords]) => ({
    char,
    name,
    keywords,
    category,
  }));
}

const SMILEYS: RawEmoji[] = [
  ["\u{1F600}", "grinning face", ["smile", "happy", "grin"]],
  ["\u{1F603}", "grinning face with big eyes", ["smile", "happy", "joy"]],
  ["\u{1F604}", "grinning face with smiling eyes", ["smile", "happy", "joy"]],
  ["\u{1F601}", "beaming face with smiling eyes", ["smile", "happy", "grin"]],
  ["\u{1F606}", "grinning squinting face", ["laugh", "happy", "haha"]],
  ["\u{1F605}", "grinning face with sweat", ["laugh", "relief", "phew"]],
  ["\u{1F923}", "rolling on the floor laughing", ["lol", "rofl", "haha"]],
  ["\u{1F602}", "face with tears of joy", ["lol", "laugh", "haha", "joy"]],
  ["\u{1F642}", "slightly smiling face", ["smile", "happy"]],
  ["\u{1F643}", "upside-down face", ["silly", "sarcasm"]],
  ["\u{1F609}", "winking face", ["wink", "flirt"]],
  ["\u{1F60A}", "smiling face with smiling eyes", ["blush", "happy", "warm"]],
  ["\u{1F607}", "smiling face with halo", ["angel", "innocent", "good"]],
  ["\u{1F970}", "smiling face with hearts", ["love", "affection", "crush"]],
  ["\u{1F60D}", "smiling face with heart-eyes", ["love", "crush", "adore"]],
  ["\u{1F929}", "star-struck", ["wow", "amazed", "excited"]],
  ["\u{1F618}", "face blowing a kiss", ["kiss", "love", "flirt"]],
  ["\u{1F617}", "kissing face", ["kiss", "love"]],
  ["\u{1F61A}", "kissing face with closed eyes", ["kiss", "love"]],
  ["\u{1F619}", "kissing face with smiling eyes", ["kiss", "love"]],
  ["\u{1F972}", "smiling face with tear", ["touched", "grateful", "proud"]],
  ["\u{1F60B}", "face savoring food", ["yum", "delicious", "tasty"]],
  ["\u{1F61B}", "face with tongue", ["tongue", "playful", "silly"]],
  ["\u{1F61C}", "winking face with tongue", ["tongue", "playful", "silly"]],
  ["\u{1F92A}", "zany face", ["crazy", "wild", "silly"]],
  ["\u{1F61D}", "squinting face with tongue", ["tongue", "haha", "joke"]],
  ["\u{1F911}", "money-mouth face", ["money", "rich", "cash"]],
  ["\u{1F917}", "hugging face", ["hug", "warm", "care"]],
  ["\u{1F92D}", "face with hand over mouth", ["oops", "shock", "giggle"]],
  ["\u{1F92B}", "shushing face", ["quiet", "secret", "shh"]],
  ["\u{1F914}", "thinking face", ["think", "hmm", "consider"]],
  ["\u{1F910}", "zipper-mouth face", ["secret", "quiet", "silence"]],
  ["\u{1F928}", "face with raised eyebrow", ["skeptical", "suspicious", "doubt"]],
  ["\u{1F610}", "neutral face", ["meh", "blank", "indifferent"]],
  ["\u{1F611}", "expressionless face", ["meh", "blank", "flat"]],
  ["\u{1F636}", "face without mouth", ["silent", "speechless"]],
  ["\u{1F60F}", "smirking face", ["smirk", "sly", "flirt"]],
  ["\u{1F612}", "unamused face", ["annoyed", "meh", "bored"]],
  ["\u{1F644}", "face with rolling eyes", ["eyeroll", "annoyed", "whatever"]],
  ["\u{1F62C}", "grimacing face", ["awkward", "cringe", "nervous"]],
  ["\u{1F925}", "lying face", ["lie", "pinocchio", "liar"]],
  ["\u{1F60C}", "relieved face", ["relief", "calm", "phew"]],
  ["\u{1F614}", "pensive face", ["sad", "thoughtful", "sigh"]],
  ["\u{1F62A}", "sleepy face", ["tired", "sleepy", "yawn"]],
  ["\u{1F924}", "drooling face", ["drool", "hungry", "want"]],
  ["\u{1F634}", "sleeping face", ["sleep", "zzz", "tired"]],
  ["\u{1F637}", "face with medical mask", ["sick", "mask", "ill"]],
  ["\u{1F912}", "face with thermometer", ["sick", "fever", "ill"]],
  ["\u{1F915}", "face with head-bandage", ["hurt", "injured", "pain"]],
  ["\u{1F922}", "nauseated face", ["sick", "gross", "ill"]],
  ["\u{1F92E}", "face vomiting", ["sick", "gross", "ill"]],
  ["\u{1F927}", "sneezing face", ["sick", "allergy", "achoo"]],
  ["\u{1F975}", "hot face", ["hot", "sweat", "heat"]],
  ["\u{1F976}", "cold face", ["cold", "freezing", "ice"]],
  ["\u{1F974}", "woozy face", ["dizzy", "confused", "drunk"]],
  ["\u{1F635}", "dizzy face", ["dizzy", "confused", "stars"]],
  ["\u{1F92F}", "exploding head", ["mindblown", "shock", "wow"]],
  ["\u{1F973}", "partying face", ["party", "celebrate", "birthday"]],
  ["\u{1F60E}", "smiling face with sunglasses", ["cool", "swag", "confident"]],
  ["\u{1F913}", "nerd face", ["nerd", "geek", "smart"]],
  ["\u{1F9D0}", "face with monocle", ["curious", "inspect", "fancy"]],
  ["\u{1F622}", "crying face", ["sad", "cry", "tears"]],
  ["\u{1F62D}", "loudly crying face", ["sad", "cry", "sob"]],
  ["\u{1F621}", "pouting face", ["angry", "mad", "rage"]],
  ["\u{1F620}", "angry face", ["angry", "mad", "annoyed"]],
  ["\u{1F631}", "face screaming in fear", ["scared", "shock", "scream"]],
  ["\u{1F628}", "fearful face", ["scared", "afraid", "worried"]],
];

const GESTURES: RawEmoji[] = [
  ["\u{1F44B}", "waving hand", ["wave", "hello", "bye"]],
  ["\u{1F91A}", "raised back of hand", ["hand", "stop"]],
  ["\u{1F590}\u{FE0F}", "hand with fingers splayed", ["hand", "stop"]],
  ["\u{270B}", "raised hand", ["hand", "stop", "high five"]],
  ["\u{1F596}", "vulcan salute", ["spock", "salute", "hand"]],
  ["\u{1F44C}", "OK hand", ["ok", "okay", "perfect"]],
  ["\u{1F90C}", "pinched fingers", ["chef", "kiss", "italian"]],
  ["\u{1F90F}", "pinching hand", ["small", "tiny", "little bit"]],
  ["\u{270C}\u{FE0F}", "victory hand", ["peace", "victory"]],
  ["\u{1F91E}", "crossed fingers", ["luck", "hope", "wish"]],
  ["\u{1F91F}", "love-you gesture", ["love", "ily", "hand"]],
  ["\u{1F918}", "sign of the horns", ["rock", "metal", "horns"]],
  ["\u{1F919}", "call me hand", ["shaka", "call", "hand"]],
  ["\u{1F448}", "backhand index pointing left", ["point", "left"]],
  ["\u{1F449}", "backhand index pointing right", ["point", "right"]],
  ["\u{1F446}", "backhand index pointing up", ["point", "up"]],
  ["\u{1F595}", "middle finger", ["rude", "flip off"]],
  ["\u{1F447}", "backhand index pointing down", ["point", "down"]],
  ["\u{261D}\u{FE0F}", "index pointing up", ["point", "up", "one"]],
  ["\u{1F44D}", "thumbs up", ["like", "yes", "approve", "good"]],
  ["\u{1F44E}", "thumbs down", ["dislike", "no", "bad"]],
  ["\u{270A}", "raised fist", ["fist", "power", "solidarity"]],
  ["\u{1F44A}", "oncoming fist", ["fist bump", "punch"]],
  ["\u{1F91B}", "left-facing fist", ["fist bump", "punch"]],
  ["\u{1F91C}", "right-facing fist", ["fist bump", "punch"]],
  ["\u{1F44F}", "clapping hands", ["clap", "applause", "bravo"]],
  ["\u{1F64C}", "raising hands", ["celebrate", "praise", "yay"]],
  ["\u{1F450}", "open hands", ["hug", "open", "hands"]],
  ["\u{1F932}", "palms up together", ["prayer", "gift", "cupped"]],
  ["\u{1F64F}", "folded hands", ["pray", "please", "thanks"]],
  ["\u{270D}\u{FE0F}", "writing hand", ["write", "signature"]],
  ["\u{1F485}", "nail polish", ["manicure", "nails"]],
  ["\u{1F933}", "selfie", ["photo", "selfie"]],
  ["\u{1F4AA}", "flexed biceps", ["muscle", "strong", "gym"]],
  ["\u{1F9BE}", "mechanical arm", ["robot", "arm", "prosthetic"]],
  ["\u{1F58A}\u{FE0F}", "pen", ["write", "pen"]],
  ["\u{1FAE1}", "saluting face", ["salute", "yes sir"]],
  ["\u{1FAF6}", "heart hands", ["love", "heart", "hands"]],
  ["\u{1F91D}", "handshake", ["deal", "agreement", "shake"]],
];

const PEOPLE: RawEmoji[] = [
  ["\u{1F476}", "baby", ["infant", "child"]],
  ["\u{1F9D2}", "child", ["kid", "young"]],
  ["\u{1F466}", "boy", ["kid", "child"]],
  ["\u{1F467}", "girl", ["kid", "child"]],
  ["\u{1F9D1}", "person", ["human", "adult"]],
  ["\u{1F468}", "man", ["adult", "guy"]],
  ["\u{1F469}", "woman", ["adult", "lady"]],
  ["\u{1F9D3}", "older person", ["senior", "elder"]],
  ["\u{1F474}", "old man", ["senior", "grandpa"]],
  ["\u{1F475}", "old woman", ["senior", "grandma"]],
  ["\u{1F64D}", "person frowning", ["upset", "sad"]],
  ["\u{1F64E}", "person pouting", ["annoyed", "upset"]],
  ["\u{1F645}", "person gesturing no", ["no", "denied"]],
  ["\u{1F646}", "person gesturing OK", ["ok", "yes"]],
  ["\u{1F481}", "person tipping hand", ["info", "help", "assist"]],
  ["\u{1F64B}", "person raising hand", ["question", "here", "raise"]],
  ["\u{1F9CF}", "deaf person", ["deaf", "hearing"]],
  ["\u{1F647}", "person bowing", ["bow", "sorry", "apology"]],
  ["\u{1F926}", "person facepalming", ["facepalm", "ugh", "smh"]],
  ["\u{1F937}", "person shrugging", ["shrug", "unsure", "idk"]],
  ["\u{1F46E}", "police officer", ["cop", "law"]],
  ["\u{1F575}\u{FE0F}", "detective", ["spy", "sleuth"]],
  ["\u{1F482}", "guard", ["security", "guard"]],
  ["\u{1F977}", "ninja", ["stealth", "ninja"]],
  ["\u{1F477}", "construction worker", ["builder", "worker"]],
  ["\u{1F934}", "prince", ["royal", "crown"]],
  ["\u{1F478}", "princess", ["royal", "crown"]],
  ["\u{1F473}", "person wearing turban", ["turban"]],
  ["\u{1F472}", "person with skullcap", ["cap"]],
  ["\u{1F9D5}", "woman with headscarf", ["hijab", "headscarf"]],
  ["\u{1F935}", "person in tuxedo", ["formal", "wedding"]],
  ["\u{1F470}", "person with veil", ["bride", "wedding"]],
  ["\u{1F930}", "pregnant woman", ["pregnant", "baby"]],
  ["\u{1F931}", "breast-feeding", ["baby", "nursing"]],
  ["\u{1F47C}", "baby angel", ["cherub", "angel"]],
  ["\u{1F385}", "Santa Claus", ["christmas", "santa"]],
  ["\u{1F936}", "Mrs. Claus", ["christmas", "santa"]],
  ["\u{1F9B8}", "superhero", ["hero", "cape"]],
  ["\u{1F9B9}", "supervillain", ["villain", "evil"]],
  ["\u{1F9D9}", "mage", ["wizard", "magic"]],
  ["\u{1F9DA}", "fairy", ["magic", "wings"]],
  ["\u{1F9DB}", "vampire", ["halloween", "fangs"]],
  ["\u{1F9DC}", "merperson", ["mermaid", "ocean"]],
  ["\u{1F9DD}", "elf", ["fantasy", "elf"]],
  ["\u{1F9DE}", "genie", ["magic", "wish"]],
  ["\u{1F9DF}", "zombie", ["halloween", "undead"]],
  ["\u{1F486}", "person getting massage", ["spa", "relax"]],
  ["\u{1F487}", "person getting haircut", ["barber", "salon"]],
  ["\u{1F6B6}", "person walking", ["walk", "stroll"]],
  ["\u{1F9CD}", "person standing", ["stand"]],
  ["\u{1F9CE}", "person kneeling", ["kneel"]],
  ["\u{1F3C3}", "person running", ["run", "jog", "sprint"]],
  ["\u{1F46F}", "people with bunny ears", ["party", "dance"]],
  ["\u{1F57A}", "man dancing", ["dance", "party"]],
  ["\u{1F483}", "woman dancing", ["dance", "party"]],
  ["\u{1F46B}", "man and woman holding hands", ["couple", "date"]],
  ["\u{1F46C}", "two men holding hands", ["couple", "pride"]],
  ["\u{1F46D}", "two women holding hands", ["couple", "pride"]],
  ["\u{1F48F}", "kiss", ["couple", "romance"]],
  ["\u{1F491}", "couple with heart", ["couple", "love"]],
  ["\u{1F46A}", "family", ["family", "parents", "kids"]],
];

const ANIMALS: RawEmoji[] = [
  ["\u{1F436}", "dog face", ["dog", "puppy", "pet"]],
  ["\u{1F431}", "cat face", ["cat", "kitten", "pet"]],
  ["\u{1F42D}", "mouse face", ["mouse", "rodent"]],
  ["\u{1F439}", "hamster face", ["hamster", "pet"]],
  ["\u{1F430}", "rabbit face", ["rabbit", "bunny"]],
  ["\u{1F98A}", "fox", ["fox", "sly"]],
  ["\u{1F43B}", "bear", ["bear"]],
  ["\u{1F43C}", "panda", ["panda"]],
  ["\u{1F428}", "koala", ["koala"]],
  ["\u{1F42F}", "tiger face", ["tiger", "cat"]],
  ["\u{1F981}", "lion", ["lion", "king"]],
  ["\u{1F42E}", "cow face", ["cow"]],
  ["\u{1F437}", "pig face", ["pig"]],
  ["\u{1F438}", "frog", ["frog"]],
  ["\u{1F435}", "monkey face", ["monkey"]],
  ["\u{1F648}", "see-no-evil monkey", ["monkey", "shy", "oops"]],
  ["\u{1F649}", "hear-no-evil monkey", ["monkey", "quiet"]],
  ["\u{1F64A}", "speak-no-evil monkey", ["monkey", "secret"]],
  ["\u{1F414}", "chicken", ["chicken", "bird"]],
  ["\u{1F427}", "penguin", ["penguin", "bird"]],
  ["\u{1F426}", "bird", ["bird", "tweet"]],
  ["\u{1F424}", "baby chick", ["chick", "bird"]],
  ["\u{1F986}", "duck", ["duck", "bird"]],
  ["\u{1F985}", "eagle", ["eagle", "bird"]],
  ["\u{1F989}", "owl", ["owl", "bird", "wise"]],
  ["\u{1F987}", "bat", ["bat", "halloween"]],
  ["\u{1F43A}", "wolf", ["wolf"]],
  ["\u{1F417}", "boar", ["boar", "pig"]],
  ["\u{1F434}", "horse face", ["horse"]],
  ["\u{1F984}", "unicorn", ["unicorn", "magic"]],
  ["\u{1F41D}", "honeybee", ["bee", "insect"]],
  ["\u{1F41B}", "bug", ["bug", "caterpillar"]],
  ["\u{1F98B}", "butterfly", ["butterfly"]],
  ["\u{1F40C}", "snail", ["snail", "slow"]],
  ["\u{1F41E}", "lady beetle", ["ladybug", "insect"]],
  ["\u{1F41C}", "ant", ["ant", "insect"]],
  ["\u{1F577}\u{FE0F}", "spider", ["spider", "halloween"]],
  ["\u{1F422}", "turtle", ["turtle", "slow"]],
  ["\u{1F40D}", "snake", ["snake"]],
  ["\u{1F98E}", "lizard", ["lizard", "reptile"]],
  ["\u{1F996}", "T-Rex", ["dinosaur", "trex"]],
  ["\u{1F995}", "sauropod", ["dinosaur"]],
  ["\u{1F419}", "octopus", ["octopus", "ocean"]],
  ["\u{1F990}", "shrimp", ["shrimp", "seafood"]],
  ["\u{1F980}", "crab", ["crab", "seafood"]],
  ["\u{1F421}", "blowfish", ["fish", "puffer"]],
  ["\u{1F420}", "tropical fish", ["fish", "ocean"]],
  ["\u{1F41F}", "fish", ["fish"]],
  ["\u{1F42C}", "dolphin", ["dolphin", "ocean"]],
  ["\u{1F433}", "spouting whale", ["whale", "ocean"]],
  ["\u{1F988}", "shark", ["shark", "ocean"]],
  ["\u{1F40A}", "crocodile", ["crocodile", "alligator"]],
  ["\u{1F993}", "zebra", ["zebra"]],
  ["\u{1F98D}", "gorilla", ["gorilla", "ape"]],
  ["\u{1F418}", "elephant", ["elephant"]],
  ["\u{1F99B}", "hippopotamus", ["hippo"]],
  ["\u{1F42A}", "camel", ["camel", "desert"]],
  ["\u{1F992}", "giraffe", ["giraffe"]],
  ["\u{1F998}", "kangaroo", ["kangaroo"]],
  ["\u{1F411}", "ewe", ["sheep", "lamb"]],
  ["\u{1F999}", "llama", ["llama", "alpaca"]],
  ["\u{1F410}", "goat", ["goat"]],
  ["\u{1F98C}", "deer", ["deer"]],
  ["\u{1F415}", "dog", ["dog", "pet"]],
  ["\u{1F408}", "cat", ["cat", "pet"]],
  ["\u{1F413}", "rooster", ["rooster", "chicken"]],
  ["\u{1F983}", "turkey", ["turkey", "thanksgiving"]],
  ["\u{1F54A}\u{FE0F}", "dove", ["dove", "peace"]],
  ["\u{1F9A2}", "swan", ["swan"]],
  ["\u{1F9A9}", "flamingo", ["flamingo"]],
  ["\u{1F99A}", "peacock", ["peacock"]],
  ["\u{1F99C}", "parrot", ["parrot"]],
  ["\u{1F335}", "cactus", ["cactus", "desert"]],
  ["\u{1F334}", "palm tree", ["palm", "tree", "tropical"]],
  ["\u{1F331}", "seedling", ["plant", "grow"]],
  ["\u{1F340}", "four leaf clover", ["luck", "clover"]],
  ["\u{1F342}", "fallen leaf", ["autumn", "leaf"]],
  ["\u{1F337}", "tulip", ["flower", "tulip"]],
  ["\u{1F339}", "rose", ["flower", "rose", "love"]],
  ["\u{1F33B}", "sunflower", ["flower", "sunflower"]],
];

const FOOD: RawEmoji[] = [
  ["\u{1F347}", "grapes", ["fruit", "grapes"]],
  ["\u{1F349}", "watermelon", ["fruit", "summer"]],
  ["\u{1F34A}", "tangerine", ["fruit", "orange"]],
  ["\u{1F34B}", "lemon", ["fruit", "sour"]],
  ["\u{1F34C}", "banana", ["fruit", "banana"]],
  ["\u{1F34D}", "pineapple", ["fruit", "tropical"]],
  ["\u{1F96D}", "mango", ["fruit", "mango"]],
  ["\u{1F34E}", "red apple", ["fruit", "apple"]],
  ["\u{1F350}", "pear", ["fruit", "pear"]],
  ["\u{1F351}", "peach", ["fruit", "peach"]],
  ["\u{1F352}", "cherries", ["fruit", "cherry"]],
  ["\u{1F353}", "strawberry", ["fruit", "berry"]],
  ["\u{1FAD0}", "blueberries", ["fruit", "berry"]],
  ["\u{1F95D}", "kiwi fruit", ["fruit", "kiwi"]],
  ["\u{1F345}", "tomato", ["vegetable", "tomato"]],
  ["\u{1F965}", "coconut", ["fruit", "coconut"]],
  ["\u{1F951}", "avocado", ["fruit", "avocado"]],
  ["\u{1F346}", "eggplant", ["vegetable", "eggplant"]],
  ["\u{1F955}", "carrot", ["vegetable", "carrot"]],
  ["\u{1F33D}", "ear of corn", ["vegetable", "corn"]],
  ["\u{1F336}\u{FE0F}", "hot pepper", ["spicy", "chili"]],
  ["\u{1F952}", "cucumber", ["vegetable", "cucumber"]],
  ["\u{1F966}", "broccoli", ["vegetable", "broccoli"]],
  ["\u{1F344}", "mushroom", ["mushroom", "fungus"]],
  ["\u{1F95C}", "peanuts", ["nuts", "peanuts"]],
  ["\u{1F35E}", "bread", ["bread", "bakery"]],
  ["\u{1F950}", "croissant", ["bread", "bakery", "french"]],
  ["\u{1F956}", "baguette bread", ["bread", "bakery", "french"]],
  ["\u{1F968}", "pretzel", ["snack", "pretzel"]],
  ["\u{1F96F}", "bagel", ["bread", "bakery"]],
  ["\u{1F95E}", "pancakes", ["breakfast", "pancakes"]],
  ["\u{1F9C0}", "cheese wedge", ["cheese", "dairy"]],
  ["\u{1F356}", "meat on bone", ["meat", "food"]],
  ["\u{1F357}", "poultry leg", ["chicken", "meat"]],
  ["\u{1F969}", "cut of meat", ["meat", "steak"]],
  ["\u{1F953}", "bacon", ["bacon", "breakfast"]],
  ["\u{1F354}", "hamburger", ["burger", "fast food"]],
  ["\u{1F35F}", "french fries", ["fries", "fast food"]],
  ["\u{1F355}", "pizza", ["pizza", "food"]],
  ["\u{1F32D}", "hot dog", ["hotdog", "fast food"]],
  ["\u{1F96A}", "sandwich", ["sandwich", "lunch"]],
  ["\u{1F32E}", "taco", ["taco", "mexican"]],
  ["\u{1F32F}", "burrito", ["burrito", "mexican"]],
  ["\u{1F95F}", "dumpling", ["dumpling", "asian food"]],
  ["\u{1F373}", "cooking", ["egg", "fried egg"]],
  ["\u{1FAD3}", "tamale", ["mexican", "food"]],
  ["\u{1F958}", "shallow pan of food", ["paella", "food"]],
  ["\u{1F372}", "pot of food", ["stew", "food"]],
  ["\u{1F963}", "bowl with spoon", ["cereal", "breakfast"]],
  ["\u{1F957}", "green salad", ["salad", "healthy"]],
  ["\u{1F37F}", "popcorn", ["popcorn", "movie"]],
  ["\u{1F371}", "bento box", ["lunch", "japanese"]],
  ["\u{1F359}", "rice ball", ["rice", "japanese"]],
  ["\u{1F35A}", "cooked rice", ["rice", "food"]],
  ["\u{1F35B}", "curry rice", ["curry", "food"]],
  ["\u{1F35C}", "steaming bowl", ["ramen", "noodles"]],
  ["\u{1F35D}", "spaghetti", ["pasta", "italian"]],
  ["\u{1F363}", "sushi", ["sushi", "japanese"]],
  ["\u{1F364}", "fried shrimp", ["tempura", "food"]],
  ["\u{1F368}", "ice cream", ["dessert", "ice cream"]],
  ["\u{1F369}", "doughnut", ["dessert", "donut"]],
  ["\u{1F36A}", "cookie", ["dessert", "cookie"]],
  ["\u{1F382}", "birthday cake", ["cake", "birthday", "party"]],
  ["\u{1F370}", "shortcake", ["dessert", "cake"]],
  ["\u{1F9C1}", "cupcake", ["dessert", "cupcake"]],
  ["\u{1F967}", "pie", ["dessert", "pie"]],
  ["\u{1F36B}", "chocolate bar", ["chocolate", "candy"]],
  ["\u{1F36C}", "candy", ["candy", "sweet"]],
  ["\u{1F36D}", "lollipop", ["candy", "sweet"]],
  ["\u{1F36F}", "honey pot", ["honey", "sweet"]],
  ["\u{2615}", "hot beverage", ["coffee", "tea"]],
  ["\u{1F375}", "teacup without handle", ["tea", "drink"]],
  ["\u{1F377}", "wine glass", ["wine", "drink"]],
  ["\u{1F378}", "cocktail glass", ["cocktail", "drink"]],
  ["\u{1F379}", "tropical drink", ["cocktail", "drink"]],
  ["\u{1F37A}", "beer mug", ["beer", "drink"]],
  ["\u{1F37B}", "clinking beer mugs", ["beer", "cheers", "drink"]],
  ["\u{1F942}", "clinking glasses", ["cheers", "drink", "toast"]],
];

const ACTIVITIES: RawEmoji[] = [
  ["\u{26BD}", "soccer ball", ["sports", "football", "soccer"]],
  ["\u{1F3C0}", "basketball", ["sports", "basketball"]],
  ["\u{1F3C8}", "american football", ["sports", "football"]],
  ["\u{26BE}", "baseball", ["sports", "baseball"]],
  ["\u{1F3BE}", "tennis", ["sports", "tennis"]],
  ["\u{1F3D0}", "volleyball", ["sports", "volleyball"]],
  ["\u{1F3C9}", "rugby football", ["sports", "rugby"]],
  ["\u{1F3B1}", "pool 8 ball", ["billiards", "pool"]],
  ["\u{1F3D3}", "ping pong", ["table tennis", "sports"]],
  ["\u{1F3F8}", "badminton", ["sports", "badminton"]],
  ["\u{1F3D2}", "ice hockey", ["sports", "hockey"]],
  ["\u{1F3CF}", "cricket game", ["sports", "cricket"]],
  ["\u{1F94A}", "boxing glove", ["boxing", "fight", "sports"]],
  ["\u{1F94B}", "martial arts uniform", ["karate", "judo", "sports"]],
  ["\u{1F6F9}", "skateboard", ["sports", "skate"]],
  ["\u{1F6F7}", "sled", ["winter", "sledding"]],
  ["\u{26F8}\u{FE0F}", "ice skate", ["winter", "skating"]],
  ["\u{1F3BF}", "skis", ["winter", "skiing"]],
  ["\u{1F3C2}", "snowboarder", ["winter", "snowboard"]],
  ["\u{1F3CB}\u{FE0F}", "person lifting weights", ["gym", "workout"]],
  ["\u{1F93C}", "wrestlers", ["wrestling", "sports"]],
  ["\u{1F938}", "person cartwheeling", ["gymnastics"]],
  ["\u{1F93A}", "person fencing", ["fencing", "sports"]],
  ["\u{1F3CC}\u{FE0F}", "person golfing", ["golf", "sports"]],
  ["\u{1F9D8}", "person in lotus position", ["yoga", "meditate"]],
  ["\u{1F3C4}", "person surfing", ["surf", "ocean", "sports"]],
  ["\u{1F3CA}", "person swimming", ["swim", "pool", "sports"]],
  ["\u{1F6A3}", "person rowing boat", ["rowing", "sports"]],
  ["\u{1F9D7}", "person climbing", ["climbing", "sports"]],
  ["\u{1F6B4}", "person biking", ["cycling", "bike"]],
  ["\u{1F3C6}", "trophy", ["award", "win", "champion"]],
  ["\u{1F947}", "1st place medal", ["gold", "first", "winner"]],
  ["\u{1F948}", "2nd place medal", ["silver", "second"]],
  ["\u{1F949}", "3rd place medal", ["bronze", "third"]],
  ["\u{1F3C5}", "sports medal", ["medal", "award"]],
  ["\u{1F3AB}", "ticket", ["event", "ticket"]],
  ["\u{1F3AA}", "circus tent", ["circus", "show"]],
  ["\u{1F939}", "person juggling", ["juggle", "circus"]],
  ["\u{1F3AD}", "performing arts", ["theater", "drama"]],
  ["\u{1F3A8}", "artist palette", ["art", "paint"]],
  ["\u{1F3AC}", "clapper board", ["movie", "film"]],
  ["\u{1F3A4}", "microphone", ["sing", "karaoke"]],
  ["\u{1F3A7}", "headphone", ["music", "audio"]],
  ["\u{1F3B9}", "musical keyboard", ["piano", "music"]],
  ["\u{1F941}", "drum", ["music", "drum"]],
  ["\u{1F3B7}", "saxophone", ["music", "jazz"]],
  ["\u{1F3BA}", "trumpet", ["music", "brass"]],
  ["\u{1F3B8}", "guitar", ["music", "guitar"]],
  ["\u{1FA95}", "banjo", ["music", "banjo"]],
  ["\u{1F3BB}", "violin", ["music", "violin"]],
  ["\u{1F3B2}", "game die", ["dice", "game"]],
  ["\u{1F3AF}", "direct hit", ["dart", "target", "bullseye"]],
  ["\u{1F3B3}", "bowling", ["bowling", "sports"]],
  ["\u{1F3AE}", "video game controller", ["gaming", "controller"]],
  ["\u{1F579}\u{FE0F}", "joystick", ["gaming", "arcade"]],
  ["\u{1F9E9}", "puzzle piece", ["puzzle", "jigsaw"]],
];

const TRAVEL: RawEmoji[] = [
  ["\u{1F697}", "automobile", ["car", "drive"]],
  ["\u{1F695}", "taxi", ["cab", "car"]],
  ["\u{1F699}", "sport utility vehicle", ["suv", "car"]],
  ["\u{1F68C}", "bus", ["bus", "transit"]],
  ["\u{1F3CE}\u{FE0F}", "racing car", ["race", "car", "fast"]],
  ["\u{1F693}", "police car", ["police", "car"]],
  ["\u{1F691}", "ambulance", ["hospital", "emergency"]],
  ["\u{1F692}", "fire engine", ["fire truck", "emergency"]],
  ["\u{1F690}", "minibus", ["van", "transit"]],
  ["\u{1F69A}", "delivery truck", ["truck", "delivery"]],
  ["\u{1F69C}", "tractor", ["farm", "tractor"]],
  ["\u{1F6F5}", "motor scooter", ["scooter", "moped"]],
  ["\u{1F3CD}\u{FE0F}", "motorcycle", ["moto", "bike"]],
  ["\u{1F6B2}", "bicycle", ["bike", "cycling"]],
  ["\u{1F6F4}", "kick scooter", ["scooter"]],
  ["\u{1F681}", "helicopter", ["chopper", "fly"]],
  ["\u{1F682}", "locomotive", ["train"]],
  ["\u{1F686}", "train", ["train", "rail"]],
  ["\u{1F687}", "metro", ["subway", "metro"]],
  ["\u{1F68A}", "tram", ["tram", "transit"]],
  ["\u{2708}\u{FE0F}", "airplane", ["fly", "travel", "plane"]],
  ["\u{1F6EB}", "airplane departure", ["takeoff", "travel"]],
  ["\u{1F6EC}", "airplane arrival", ["landing", "travel"]],
  ["\u{1F4BA}", "seat", ["seat", "flight"]],
  ["\u{1F680}", "rocket", ["space", "launch"]],
  ["\u{1F6F8}", "flying saucer", ["ufo", "alien"]],
  ["\u{26F5}", "sailboat", ["boat", "sail"]],
  ["\u{1F6A4}", "speedboat", ["boat", "speed"]],
  ["\u{1F6A2}", "ship", ["cruise", "ship"]],
  ["\u{2693}", "anchor", ["boat", "anchor"]],
  ["\u{1F5FA}\u{FE0F}", "world map", ["map", "travel"]],
  ["\u{1F5FD}", "Statue of Liberty", ["nyc", "usa", "landmark"]],
  ["\u{1F5FC}", "Tokyo Tower", ["japan", "landmark"]],
  ["\u{1F3F0}", "castle", ["castle", "fairy tale"]],
  ["\u{1F3A1}", "ferris wheel", ["carnival", "fair"]],
  ["\u{1F3A2}", "roller coaster", ["amusement park", "thrill"]],
  ["\u{1F3D6}\u{FE0F}", "beach with umbrella", ["beach", "vacation"]],
  ["\u{1F3DD}\u{FE0F}", "desert island", ["island", "tropical"]],
  ["\u{1F3DC}\u{FE0F}", "desert", ["sand", "dry"]],
  ["\u{1F30B}", "volcano", ["eruption", "lava"]],
  ["\u{26F0}\u{FE0F}", "mountain", ["hiking", "peak"]],
  ["\u{1F3D4}\u{FE0F}", "snow-capped mountain", ["hiking", "snow"]],
  ["\u{1F5FB}", "mount fuji", ["japan", "mountain"]],
  ["\u{1F3D5}\u{FE0F}", "camping", ["camp", "outdoors"]],
  ["\u{26FA}", "tent", ["camp", "outdoors"]],
  ["\u{1F30D}", "globe showing Europe-Africa", ["world", "earth", "travel"]],
  ["\u{1F30E}", "globe showing Americas", ["world", "earth", "travel"]],
  ["\u{1F30F}", "globe showing Asia-Australia", ["world", "earth", "travel"]],
  ["\u{1F9F3}", "luggage", ["suitcase", "travel", "bag"]],
  ["\u{1F30C}", "milky way", ["space", "stars", "galaxy"]],
  ["\u{1F320}", "shooting star", ["wish", "star"]],
  ["\u{2600}\u{FE0F}", "sun", ["sunny", "weather"]],
  ["\u{1F308}", "rainbow", ["colorful", "pride"]],
  ["\u{2601}\u{FE0F}", "cloud", ["weather", "cloudy"]],
  ["\u{2614}", "umbrella with rain drops", ["rain", "weather"]],
  ["\u{2744}\u{FE0F}", "snowflake", ["snow", "winter"]],
];

const OBJECTS: RawEmoji[] = [
  ["\u{231A}", "watch", ["time", "wrist"]],
  ["\u{1F4F1}", "mobile phone", ["phone", "cell"]],
  ["\u{1F4BB}", "laptop", ["computer", "work"]],
  ["\u{2328}\u{FE0F}", "keyboard", ["type", "computer"]],
  ["\u{1F5A5}\u{FE0F}", "desktop computer", ["computer", "pc"]],
  ["\u{1F5A8}\u{FE0F}", "printer", ["print", "office"]],
  ["\u{1F4F7}", "camera", ["photo", "picture"]],
  ["\u{1F4F9}", "video camera", ["video", "record"]],
  ["\u{1F3A5}", "movie camera", ["film", "movie"]],
  ["\u{260E}\u{FE0F}", "telephone", ["phone", "call"]],
  ["\u{1F4FA}", "television", ["tv", "watch"]],
  ["\u{1F4FB}", "radio", ["music", "audio"]],
  ["\u{1F50B}", "battery", ["power", "charge"]],
  ["\u{1F50C}", "electric plug", ["power", "cable"]],
  ["\u{1F4A1}", "light bulb", ["idea", "light"]],
  ["\u{1F526}", "flashlight", ["light", "torch"]],
  ["\u{1F56F}\u{FE0F}", "candle", ["light", "wax"]],
  ["\u{1F9EF}", "fire extinguisher", ["safety", "fire"]],
  ["\u{1F4B8}", "money with wings", ["spend", "money"]],
  ["\u{1F4B5}", "dollar banknote", ["money", "cash"]],
  ["\u{1F4B0}", "money bag", ["money", "rich"]],
  ["\u{1F4B3}", "credit card", ["payment", "money"]],
  ["\u{1F48E}", "gem stone", ["diamond", "jewel"]],
  ["\u{2696}\u{FE0F}", "balance scale", ["justice", "law"]],
  ["\u{1F9F0}", "toolbox", ["tools", "repair"]],
  ["\u{1F527}", "wrench", ["tools", "fix"]],
  ["\u{1F528}", "hammer", ["tools", "build"]],
  ["\u{2699}\u{FE0F}", "gear", ["settings", "config"]],
  ["\u{1F517}", "link", ["url", "chain"]],
  ["\u{1F9F2}", "magnet", ["magnetic", "attract"]],
  ["\u{1F52C}", "microscope", ["science", "lab"]],
  ["\u{1F52D}", "telescope", ["astronomy", "stars"]],
  ["\u{1F489}", "syringe", ["medical", "shot"]],
  ["\u{1F48A}", "pill", ["medicine", "medical"]],
  ["\u{1FA79}", "adhesive bandage", ["bandaid", "injury"]],
  ["\u{1FA7A}", "stethoscope", ["doctor", "medical"]],
  ["\u{1F6AA}", "door", ["entrance", "exit"]],
  ["\u{1FA91}", "chair", ["furniture", "seat"]],
  ["\u{1F6CF}\u{FE0F}", "bed", ["sleep", "furniture"]],
  ["\u{1F6BD}", "toilet", ["bathroom", "restroom"]],
  ["\u{1F6BF}", "shower", ["bathroom", "wash"]],
  ["\u{1F6C1}", "bathtub", ["bath", "bathroom"]],
  ["\u{1F9F9}", "broom", ["clean", "sweep"]],
  ["\u{1F9FC}", "soap", ["clean", "wash"]],
  ["\u{1FAA5}", "toothbrush", ["clean", "teeth"]],
  ["\u{1F4D6}", "open book", ["read", "book"]],
  ["\u{1F4DA}", "books", ["read", "library"]],
  ["\u{1F4D3}", "notebook", ["write", "notes"]],
  ["\u{1F4F0}", "newspaper", ["news", "read"]],
  ["\u{1F516}", "bookmark", ["save", "mark"]],
  ["\u{2709}\u{FE0F}", "envelope", ["mail", "email"]],
  ["\u{1F4E7}", "e-mail", ["email", "message"]],
  ["\u{1F4E6}", "package", ["box", "delivery"]],
  ["\u{1F4EB}", "closed mailbox with raised flag", ["mail", "mailbox"]],
  ["\u{270F}\u{FE0F}", "pencil", ["write", "edit"]],
  ["\u{1F58B}\u{FE0F}", "fountain pen", ["write", "signature"]],
  ["\u{1F4DD}", "memo", ["note", "write"]],
  ["\u{1F4BC}", "briefcase", ["work", "business"]],
  ["\u{1F4C1}", "file folder", ["files", "folder"]],
  ["\u{1F4C5}", "calendar", ["date", "schedule"]],
  ["\u{1F4C8}", "chart increasing", ["growth", "stats"]],
  ["\u{1F4C9}", "chart decreasing", ["decline", "stats"]],
  ["\u{1F4CA}", "bar chart", ["stats", "data"]],
  ["\u{1F4CB}", "clipboard", ["list", "tasks"]],
  ["\u{1F4CC}", "pushpin", ["pin", "location"]],
  ["\u{1F4CE}", "paperclip", ["attach", "clip"]],
  ["\u{1F4CF}", "straight ruler", ["measure", "length"]],
  ["\u{2702}\u{FE0F}", "scissors", ["cut", "trim"]],
  ["\u{1F5D1}\u{FE0F}", "wastebasket", ["trash", "delete"]],
  ["\u{1F512}", "locked", ["secure", "lock"]],
  ["\u{1F513}", "unlocked", ["open", "unlock"]],
  ["\u{1F511}", "key", ["unlock", "access"]],
  ["\u{1F6D2}", "shopping cart", ["shop", "buy", "cart"]],
];

const SYMBOLS: RawEmoji[] = [
  ["\u{2764}\u{FE0F}", "red heart", ["love", "heart"]],
  ["\u{1F9E1}", "orange heart", ["love", "heart"]],
  ["\u{1F49B}", "yellow heart", ["love", "heart"]],
  ["\u{1F49A}", "green heart", ["love", "heart"]],
  ["\u{1F499}", "blue heart", ["love", "heart"]],
  ["\u{1F49C}", "purple heart", ["love", "heart"]],
  ["\u{1F5A4}", "black heart", ["love", "heart", "dark"]],
  ["\u{1F90D}", "white heart", ["love", "heart"]],
  ["\u{1F90E}", "brown heart", ["love", "heart"]],
  ["\u{1F494}", "broken heart", ["heartbreak", "sad"]],
  ["\u{1F495}", "two hearts", ["love", "hearts"]],
  ["\u{1F49E}", "revolving hearts", ["love", "hearts"]],
  ["\u{1F493}", "beating heart", ["love", "heart"]],
  ["\u{1F497}", "growing heart", ["love", "heart"]],
  ["\u{1F496}", "sparkling heart", ["love", "heart"]],
  ["\u{1F498}", "heart with arrow", ["cupid", "love"]],
  ["\u{1F49D}", "heart with ribbon", ["gift", "love"]],
  ["\u{262E}\u{FE0F}", "peace symbol", ["peace"]],
  ["\u{262F}\u{FE0F}", "yin yang", ["balance", "harmony"]],
  ["\u{1F501}", "shuffle tracks button", ["shuffle", "music"]],
  ["\u{25B6}\u{FE0F}", "play button", ["play", "start"]],
  ["⏸\u{FE0F}", "pause button", ["pause", "stop"]],
  ["⏹\u{FE0F}", "stop button", ["stop"]],
  ["\u{2B06}\u{FE0F}", "up arrow", ["arrow", "up"]],
  ["\u{2B07}\u{FE0F}", "down arrow", ["arrow", "down"]],
  ["\u{2B05}\u{FE0F}", "left arrow", ["arrow", "left"]],
  ["\u{27A1}\u{FE0F}", "right arrow", ["arrow", "right"]],
  ["\u{1F504}", "counterclockwise arrows button", ["refresh", "reload", "sync"]],
  ["✅", "check mark button", ["done", "yes", "correct"]],
  ["✔\u{FE0F}", "check mark", ["done", "yes", "correct"]],
  ["❌", "cross mark", ["no", "wrong", "delete"]],
  ["➕", "plus", ["add", "math"]],
  ["➖", "minus", ["subtract", "math"]],
  ["✖\u{FE0F}", "multiply", ["math", "times"]],
  ["♾\u{FE0F}", "infinity", ["forever", "unlimited"]],
  ["❗", "exclamation mark", ["alert", "important"]],
  ["❓", "question mark", ["ask", "confused"]],
  ["\u{1F4AF}", "hundred points", ["100", "perfect", "score"]],
  ["\u{1F525}", "fire", ["hot", "lit", "trending"]],
  ["✨", "sparkles", ["shiny", "new", "magic"]],
  ["⭐", "star", ["favorite", "rate"]],
  ["\u{1F31F}", "glowing star", ["shine", "star"]],
  ["⚡", "high voltage", ["lightning", "power", "fast"]],
  ["\u{1F4A5}", "collision", ["boom", "impact"]],
  ["\u{1F4A2}", "anger symbol", ["mad", "angry"]],
  ["\u{1F4A4}", "zzz", ["sleep", "tired"]],
  ["\u{1F4A6}", "sweat droplets", ["sweat", "water"]],
  ["\u{1F4A8}", "dashing away", ["fast", "wind", "run"]],
];

export const EMOJI_CATALOG: EmojiEntry[] = [
  ...withCategory("smileys", SMILEYS),
  ...withCategory("gestures", GESTURES),
  ...withCategory("people", PEOPLE),
  ...withCategory("animals", ANIMALS),
  ...withCategory("food", FOOD),
  ...withCategory("activities", ACTIVITIES),
  ...withCategory("travel", TRAVEL),
  ...withCategory("objects", OBJECTS),
  ...withCategory("symbols", SYMBOLS),
];

/**
 * Case-insensitive substring match over name + keywords when `query` is
 * non-empty. Empty query returns the full catalog (optionally scoped to
 * `category`) grouped in catalog order — the panel renders section headers
 * from that same order.
 */
export function filterEmoji(query: string, category?: string): EmojiEntry[] {
  const scoped = category
    ? EMOJI_CATALOG.filter((e) => e.category === category)
    : EMOJI_CATALOG;
  const q = query.trim().toLowerCase();
  if (!q) return scoped;
  return scoped.filter((e) => {
    if (e.name.toLowerCase().includes(q)) return true;
    return e.keywords.some((k) => k.toLowerCase().includes(q));
  });
}
